version: "3"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:1.17.1-alpine
    ports:
     - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/nginx/ssl
     - /docker/stockratesbot/deploy/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "stockratesbot"
    restart: always


  stockratesbot:
    container_name: stockratesbot
    hostname: stockratesbot
    build: .
    env_file:
      - env_vars.env
    expose:
      - "8080"
    links:
      - "redis"
    restart: always


  redis:
    container_name: redis
    networks:
    image: redis:alpine
    hostname: redis
    restart: always
