version: "3"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    networks:
      - stockratesbot
    image: nginx:1.17.1-alpine
    ports:
     - "443:443"
    volumes:
     - /etc/letsencrypt:/etc/nginx/ssl
     - /docker/stockratesbot/deploy/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - "stockratesbot"
    restart: always

  stockratesbot:
    container_name: stockratesbot
    hostname: stockratesbot
    networks:
      - stockratesbot
    image: devdevregistry.azurecr.io/stockratesbot:latest
    env_file:
      - .env
    expose:
      - "8080"
    links:
      - "redis"
    depends_on:
      - "redis"
    command: ["/docker/stockratesbot/wait-for-it.sh", "redis:6379", "--", "/bin/bash", "-c", "python3.6 /docker/stockratesbot/main.py"]
    restart: always

  cronjobs:
    container_name: cronjobs
    hostname: cronjobs
    networks:
      - stockratesbot
    build:
      context: .
      dockerfile: docker/cronjob_Dockerfile/Dockerfile
    links:
      - "redis"
    restart: always

  redis:
    container_name: redis
    hostname: redis
    networks:
      - stockratesbot
    image: redis:alpine
    restart: always


networks:
  stockratesbot:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
